using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class PlaytimesManagerWindow : DefaultWindow
    {
        [Dependency] private ILocalizationManager _localization = default!;

        public PlaytimesManagerWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            UpdateType.AddItem(_localization.GetString("playtimes-manager-type-set"));
            UpdateType.SetItemMetadata(0, PlaytimeUpdateType.Set);
            UpdateType.AddItem(_localization.GetString("playtimes-manager-type-add"));
            UpdateType.SetItemMetadata(1, PlaytimeUpdateType.Add);
            UpdateType.AddItem(_localization.GetString("playtimes-manager-type-set-minimum"));
            UpdateType.SetItemMetadata(2, PlaytimeUpdateType.SetMinimum);
        }

    }
}
